import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import { Tab } from '@headlessui/react'

const inter = Inter({ subsets: ['latin'] })
const tabs = [
  {
    key: 'all',
    display: 'All'
  },
  {
    key: 'street',
    display: 'Street'
  },
  {
    key: 'portraits',
    display: 'Portraits'
  },
  {
    key: 'other',
    display: 'Other'
  }
]

export default function Home() {
  return (
    <div className='flex flex-col h-full bg-black'>
      <Head>
        <title>Ian McIntosh - Photography Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='flex justify-between items-center h-[90px] px-6'>
        <div>Portfolio</div>
        <Link href='#' className='rounded-3xl bg-white text-stone-700 px-3 py-2 hover:bg-opacity-90'>
          Get in touch
        </Link>
      </header>

      <main className='bg-black grow'>
        <div className='flex flex-col items-center h-full'>
          <Tab.Group>
            <Tab.List className='flex items-center gap-12'>
              {tabs.map((tab) => (
                <Tab key={tab.key} className='p-2'>
                  {({ selected }) => (
                    <span
                      className={selected ? 'text-white' : 'text-stone600'}
                    >
                      {tab.display}
                    </span>
                  )}
                </Tab>
              ))}
            </Tab.List>
            <Tab.Panels className='bg-stone-900 bg-opacity-30 h-full max-w-[900px] w-full p-2 sm:p-4 my-6'>
              <Tab.Panel className=''>All Photos</Tab.Panel>
              <Tab.Panel>Street Photography</Tab.Panel>
              <Tab.Panel>Portrait Photography</Tab.Panel>
              <Tab.Panel>Other Photos</Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
      </main>

      <footer className='h-[60px] flex justify-center items-center'>
        <p>Portfolio</p>
      </footer>
    </div>
  )
}
