import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import { Tab } from '@headlessui/react'
import Masonry from 'react-masonry-css'
import classNames from 'classnames'

const inter = Inter({ subsets: ['latin'] })
const tabs = [
  {
    key: 'all',
    display: 'All'
  },
  {
    key: 'street',
    display: 'Street'
  },
  {
    key: 'portraits',
    display: 'Portraits'
  },
  {
    key: 'other',
    display: 'Other'
  }
]

export default function Home() {
  return (
    <div className='flex flex-col h-full bg-black overflow-auto'>
      <Head>
        <title>Ian McIntosh - Photography Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='fixed top -0 w-full z-10 flex justify-between items-center h-[90px] px-6'>
        <span className='uppercase text-lg font-medium'>Portfolio</span>
        <Link href='#' className='rounded-3xl bg-white text-stone-700 px-3 py-2 hover:bg-opacity-90'>
          Get in touch
        </Link>
      </header>

      <main className='bg-black pt-[110px]'>
        <div className='flex flex-col items-center h-full'>
          <Tab.Group>
            <Tab.List className='flex items-center gap-12'>
              {tabs.map((tab) => (
                <Tab key={tab.key} className='p-2'>
                  {({ selected }) => (
                    <span
                      className={classNames('uppercase text-lg',selected ? 'text-white' : 'text-stone600')}
                    >
                      {tab.display}
                    </span>
                  )}
                </Tab>
              ))}
            </Tab.List>
            <Tab.Panels className='h-full max-w-[900px] w-full p-2 sm:p-4 my-6'>
              <Tab.Panel className=''>
                <Masonry breakpointCols={2} className='flex gap-4' columnClassName=''>
                  <img src='/1.jpg' alt='photo 1' className='my-4' />
                  <img src='/2.jpg' alt='photo 2' className='my-4' />
                  <img src='/3.jpg' alt='photo 3' className='my-4' />
                  <img src='/4.jpg' alt='photo 4' className='my-4' />
                  <img src='/5.jpg' alt='photo 5' className='my-4' />
                  <img src='/6.jpg' alt='photo 6' className='my-4' />
                </Masonry>
              </Tab.Panel>
              <Tab.Panel>Street Photography</Tab.Panel>
              <Tab.Panel>Portrait Photography</Tab.Panel>
              <Tab.Panel>Other Photos</Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
      </main>

      <footer className='h-[90px] flex justify-center items-center uppercase text-large font-medium'>
        <p>Portfolio</p>
      </footer>
    </div>
  )
}
